### ISSUE TITLE
Upgrade cheeriojs and option for decodeEntities: false

### ISSUE THREAD

**Issue by tommyka** [ashaffer/gulp-inline#10]
I had a problem using this plugin because it changed some qoutes in a inline eventlistener

    <div id="Banner" onclick="window.open('website', 'new window')">

became

    <div id="Banner" onclick="window.open(&apos;website&apos;, &apos;new window&apos;)">

I found after som digging that it was cheerio that modified the qoutes. Cheerio have a option for decodeEntities when set to false don't change the qoutes. This option is only added in a newer version than the one used in gulp-inline at the moment.

so i propose to upgrade cheerio and maybe make a option to set the setting in the gulp-inline plugin. og change the standard option.

**Comment by ashaffer** [comment]
I fixed this and simply made decodeEntities the default, as this was a bug.  The new version is on npm and should work for you now.

**Comment by tommyka** [comment]
Thanks

On Wed, Mar 4, 2015 at 10:13 AM, Andrew Shaffer <notifications@github.com>
wrote:

> I fixed this and simply made decodeEntities the default, as this was a
> bug. The new version is on npm and should work for you now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ashaffer/gulp-inline/issues/10#issuecomment-77121120>.
>



-- 
Hilsen
Tommy Kjær Andersen
tlf. +47 93 46 09 12
