### ISSUE TITLE
Replacing all apostrophe's with &apos;

### ISSUE THREAD

**Issue by dberube** [ashaffer/gulp-inline#17]
in v0.0.9

It is replacing apostrophe's in the HTML file (not necessarily the JS or CSS files).

For instance, in template.html, prior to running inline:
<title>David's Site</title>

After running inline successfully:
<title>David&apos;s Site</title>

I've debugged it down to inline being the cause -- I did notice a closed issue with this problem though?

**Comment by ashaffer** [comment]
Ah, sorry about that.  Fixed in 0.0.10.
