### ISSUE TITLE
Follow gulp plugin README conventions

### ISSUE THREAD

**Issue by lazd** [ashaffer/gulp-inline#2]
This plugin should follow the [gulp plugin README conventions](https://github.com/Liechtenecker/blog-gulp/blob/master/node_modules/gulp/docs/writing-a-plugin/readme-conventions.md) for consistency.

**Comment by ashaffer** [comment]
I think i'm in compliance with this now.  Let me know if its insufficient.

**Comment by lazd** [comment]
Looks good!
