### ISSUE TITLE
how to skip some js/css files?

### ISSUE THREAD

**Issue by VaJoy** [ashaffer/gulp-inline#24]
IMO, some common files should NOT be embed into HTML, could I use some attributes to skip being inline like what [grunt-embed](https://github.com/callumlocke/grunt-embed) did?

I\`ve got that JS could be skipped if ignore the attribute of `type`, but I have no idea`bout how to skip the CSS?

**Comment by aaronkahlhamer** [comment]
How would I ignore SVG and images from being converted to base64 and inlined? Something along the lines of the following would be helpful...

    gulp.task('inline-code', function(){
        gulp.src('index.asp')
        .pipe(inline({
        img: 'ignore',
        svg: 'ignore',
        css: minifyCSS()
    }))
    .pipe(gulp.dest('prod-desktop-default'));

**Comment by ashaffer** [comment]
https://github.com/ashaffer/gulp-inline/pull/25

Merged this in a few days ago.  Closing.
