### ISSUE TITLE
How about <object> ?

### ISSUE THREAD

**Issue by rafaelnco** [ashaffer/gulp-inline#34]
Instead of **img element with src attribute** or **svg element with use child element** I`m actually using **object element** in my development environment. However, theres still no support for **object element** inlining. Is it something that hard to do? Is there any way I can contribute to this?

**Comment by rafaelnco** [comment]
Ok, 7 min later **object element** element is now supported. It was a good time extending your code, as it is very well written. Thanks! The extended code isn`t much different from **img element** inlining, except for changing **src** attribute for **data** in every **object** case.

**Comment by ashaffer** [comment]
Ah, great. If you'd like, you can send a pull request and i'll merge it into the main codebase.

**Comment by rafaelnco** [comment]
@ashaffer sorry for the delay! We'll get our pull request ASAP ;)

**Comment by rafaelnco** [comment]
Also, @ashaffer, I may need write access to publish this code! I`m counting on you!

**Comment by ashaffer** [comment]
Closing thanks to your PR #36
